import { useCallback, useEffect, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, Clock3, Megaphone, Pause, Play, RefreshCw, Send, ShieldCheck, Users, X, XCircle } from 'lucide-react';
import { createPublishingAccount, getPublishingAccounts, getPublishingDeliveries, getPublishingOverview, type CreatePublishingAccountInput, type PublishingAccount, type PublishingOverview } from '../../lib/privatePublishingApi';
import { useSocket } from '../../contexts/SocketContext';
import { useToast } from '../../contexts/ToastContext';
const cards=[['totalNumbers','إجمالي أرقام السعودية',Users],['remainingNumbers','الأرقام المتبقية',Send],['contactedNumbers','تم التواصل معها',CheckCircle2],['sent','رسائل ناجحة',Activity],['failed','رسائل فاشلة',XCircle],['pending','قيد الانتظار',Clock3]] as const;
const emptyForm:CreatePublishingAccountInput={name:'',phoneNumber:'',phoneNumberId:'',businessAccountId:'',accessToken:'',dailyLimit:100,priority:0};
function statusLabel(s:string){return ({connected:'متصل',disconnected:'غير متصل',paused:'متوقف مؤقتاً',blocked:'محظور',pending:'بانتظار الربط',error:'خطأ'} as Record<string,string>)[s]??s}
export function PrivatePublishingPanel(){
 const [overview,setOverview]=useState<PublishingOverview|null>(null); const [accounts,setAccounts]=useState<PublishingAccount[]>([]); const [deliveries,setDeliveries]=useState<Array<{id:string;phoneNumber:string;status:string;createdAt:string;errorMessage:string|null}>>([]); const [loading,setLoading]=useState(true); const [showAccountForm,setShowAccountForm]=useState(false); const [form,setForm]=useState(emptyForm); const [saving,setSaving]=useState(false); const {socket}=useSocket(); const toast=useToast();
 const load=useCallback(async()=>{setLoading(true); try{const [o,a,d]=await Promise.all([getPublishingOverview(),getPublishingAccounts(),getPublishingDeliveries()]);setOverview(o);setAccounts(a);setDeliveries(d)} finally{setLoading(false)}},[]);
 useEffect(()=>{load(); const timer=window.setInterval(load,15000); return()=>window.clearInterval(timer)},[load]);
 useEffect(()=>{if(!socket)return; const refresh=()=>load(); socket.on('private-publishing:delivery',refresh); socket.on('private-publishing:campaign',refresh); return()=>{socket.off('private-publishing:delivery',refresh);socket.off('private-publishing:campaign',refresh)}},[socket,load]);
 const submitAccount=async(e:React.FormEvent)=>{e.preventDefault(); if(!form.name||!form.phoneNumber||!form.phoneNumberId||!form.businessAccountId||!form.accessToken){toast.error('يرجى تعبئة جميع الحقول المطلوبة');return} setSaving(true); try{await createPublishingAccount(form);toast.success('تمت إضافة حساب WhatsApp Business بنجاح');setForm(emptyForm);setShowAccountForm(false);await load()}catch(error){toast.error(error instanceof Error?error.message:'تعذر إضافة الحساب، تحقق من البيانات والصلاحيات')}finally{setSaving(false)}};
 const field=(key:keyof CreatePublishingAccountInput,label:string,placeholder:string,type='text')=><label className="block text-sm font-bold text-ink-700 dark:text-paper-200">{label}<input required={['name','phoneNumber','phoneNumberId','businessAccountId','accessToken'].includes(key)} type={type} value={String(form[key])} onChange={e=>setForm({...form,[key]:type==='number'?Number(e.target.value):e.target.value})} placeholder={placeholder} className="focus-ring mt-2 w-full rounded-xl border border-black/[0.1] bg-white/70 px-3 py-2.5 text-sm font-normal text-ink-900 placeholder:text-ink-400 dark:border-white/[0.1] dark:bg-white/[0.05] dark:text-paper-50" /></label>;
 return <section dir="rtl" className="space-y-6">
  <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-amber-600"><Megaphone className="h-5 w-5"/><span className="text-xs font-bold uppercase tracking-[0.16em]">قسم النشر ع الخاص</span></div><h1 className="font-display text-3xl font-black text-ink-950 dark:text-paper-50">النشر ع الخاص</h1><p className="mt-2 max-w-2xl text-sm text-ink-500 dark:text-paper-400">إدارة حملات WhatsApp Business الرسمية للأرقام السعودية التي تمتلك موافقة مسبقة، مع جدولة ومراقبة لحظية ومنع تكرار الإرسال.</p></div><button onClick={load} className="focus-ring inline-flex items-center justify-center gap-2 rounded-xl border border-black/[0.08] px-4 py-2.5 text-sm font-bold text-ink-700 hover:bg-black/[0.04] dark:border-white/[0.1] dark:text-paper-200"><RefreshCw className={loading?'h-4 w-4 animate-spin':'h-4 w-4'}/> تحديث</button></div>
  <div className="rounded-2xl border border-amber-500/20 bg-amber-500/10 p-4 text-sm text-amber-900 dark:text-amber-100"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0"/><p><strong>ضوابط الامتثال مفعّلة:</strong> الإرسال مصمم عبر WhatsApp Business Cloud API والقوالب المعتمدة فقط. لا يتم الإرسال إلا للمستلمين الذين سجّلوا موافقة مسبقة، ولا تُستخدم أتمتة WhatsApp Web أو أساليب تجاوز الحماية.</p></div></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([key,label,Icon])=><div key={key} className="glass-panel-solid p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold text-ink-500 dark:text-paper-400">{label}</span><Icon className="h-4 w-4 text-amber-500"/></div><p className="mt-3 text-2xl font-black tabular-nums text-ink-950 dark:text-paper-50">{overview?.[key]??'—'}</p></div>)}</div>
  <div className="grid gap-6 xl:grid-cols-[1.1fr_1fr]"><div className="glass-panel-solid overflow-hidden"><div className="flex items-center justify-between border-b border-black/[0.06] px-5 py-4 dark:border-white/[0.08]"><div><h2 className="font-display text-lg font-bold text-ink-950 dark:text-paper-50">حسابات WhatsApp Business</h2><p className="mt-1 text-xs text-ink-400">حسابات مستقلة مع حدود إرسال قابلة للضبط</p></div><button onClick={()=>setShowAccountForm(true)} className="focus-ring rounded-xl bg-amber-500 px-3 py-2 text-xs font-bold text-ink-950"><Users className="ml-1 inline h-4 w-4"/> إضافة حساب</button></div><div className="divide-y divide-black/[0.06] dark:divide-white/[0.08]">{accounts.length===0?<div className="p-8 text-center text-sm text-ink-400">لم تتم إضافة حسابات نشر بعد.</div>:accounts.map(a=><div key={a.id} className="flex items-center justify-between gap-3 px-5 py-4"><div className="min-w-0"><p className="truncate text-sm font-bold text-ink-900 dark:text-paper-100">{a.name}</p><p className="mt-1 text-xs text-ink-400">{a.phoneNumber} · أولوية {a.priority}</p></div><div className="text-left"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${a.status==='connected'?'bg-emerald-500/10 text-emerald-600':'bg-black/[0.05] text-ink-500'}`}>{statusLabel(a.status)}</span><p className="mt-1 text-[11px] text-ink-400">{a.successCount} ناجحة / {a.failedCount} فاشلة</p></div></div>)}</div></div>
  <div className="glass-panel-solid overflow-hidden"><div className="flex items-center justify-between border-b border-black/[0.06] px-5 py-4 dark:border-white/[0.08]"><div><h2 className="font-display text-lg font-bold text-ink-950 dark:text-paper-50">العمليات المباشرة</h2><p className="mt-1 text-xs text-ink-400">تُحدّث تلقائياً كل 15 ثانية أو عند وصول حدث</p></div><span className="flex items-center gap-1 text-xs font-bold text-emerald-600"><span className="h-2 w-2 rounded-full bg-emerald-500"/> لحظي</span></div><div className="max-h-[340px] overflow-auto">{deliveries.length===0?<div className="p-8 text-center text-sm text-ink-400">لا توجد عمليات مسجلة بعد.</div>:<table className="w-full text-right text-xs"><thead className="sticky top-0 bg-paper-50/95 text-ink-400 dark:bg-ink-850/95"><tr><th className="px-5 py-3">الرقم</th><th className="px-3 py-3">الحالة</th><th className="px-3 py-3">الوقت</th></tr></thead><tbody className="divide-y divide-black/[0.05] dark:divide-white/[0.06]">{deliveries.map(d=><tr key={d.id}><td className="px-5 py-3 font-mono">{d.phoneNumber}</td><td className="px-3 py-3"><span className="rounded-full bg-black/[0.05] px-2 py-1 font-bold">{statusLabel(d.status)}</span></td><td className="px-3 py-3 text-ink-400">{new Date(d.createdAt).toLocaleString('ar-SA')}</td></tr>)}</tbody></table>}</div></div></div>
  <div className="grid gap-4 sm:grid-cols-3"><button className="focus-ring glass-panel-solid flex items-center justify-center gap-2 p-4 text-sm font-bold text-ink-700 hover:border-amber-500/30 dark:text-paper-200"><Play className="h-4 w-4 text-emerald-500"/> إنشاء حملة</button><button className="focus-ring glass-panel-solid flex items-center justify-center gap-2 p-4 text-sm font-bold text-ink-700 hover:border-amber-500/30 dark:text-paper-200"><Pause className="h-4 w-4 text-amber-500"/> الجدولة</button><button className="focus-ring glass-panel-solid flex items-center justify-center gap-2 p-4 text-sm font-bold text-ink-700 hover:border-amber-500/30 dark:text-paper-200"><AlertTriangle className="h-4 w-4 text-rose-500"/> سجل الأخطاء</button></div>
  {showAccountForm&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-ink-950/50 p-4 backdrop-blur-sm"><form onSubmit={submitAccount} className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl border border-black/[0.08] bg-paper-50 p-6 shadow-2xl dark:border-white/[0.1] dark:bg-ink-850"><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="font-display text-xl font-black text-ink-950 dark:text-paper-50">إضافة حساب WhatsApp Business</h2><p className="mt-1 text-xs text-ink-500 dark:text-paper-400">سيتم تشفير Access Token وتخزينه في الخادم فقط.</p></div><button type="button" onClick={()=>setShowAccountForm(false)} className="focus-ring rounded-full p-2 text-ink-400 hover:bg-black/[0.05] dark:hover:bg-white/[0.08]" aria-label="إغلاق"><X className="h-5 w-5"/></button></div><div className="grid gap-4 sm:grid-cols-2">{field('name','اسم الحساب','حساب التسويق الرئيسي')}{field('phoneNumber','رقم WhatsApp','+9665xxxxxxxx')}{field('phoneNumberId','Phone Number ID','معرّف رقم الهاتف من Meta')}{field('businessAccountId','Business Account ID','معرّف حساب الأعمال')}{field('dailyLimit','الحد اليومي','100','number')}{field('priority','الأولوية','0','number')}</div><label className="mt-4 block text-sm font-bold text-ink-700 dark:text-paper-200">Access Token<input required type="password" value={form.accessToken} onChange={e=>setForm({...form,accessToken:e.target.value})} placeholder="أدخل الرمز السري" className="focus-ring mt-2 w-full rounded-xl border border-black/[0.1] bg-white/70 px-3 py-2.5 text-sm font-normal dark:border-white/[0.1] dark:bg-white/[0.05] dark:text-paper-50"/></label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setShowAccountForm(false)} className="focus-ring rounded-xl border border-black/[0.1] px-4 py-2.5 text-sm font-bold text-ink-700 dark:border-white/[0.1] dark:text-paper-200">إلغاء</button><button disabled={saving} className="focus-ring rounded-xl bg-amber-500 px-5 py-2.5 text-sm font-bold text-ink-950 disabled:cursor-wait disabled:opacity-60">{saving?'جارٍ الحفظ…':'حفظ الحساب'}</button></div></form></div>}
 </section>
}
